### ISSUE TITLE
Empty data values

### ISSUE THREAD

**Issue by jesusff** [jesusff/cmip6-for-cordex#1]
Empty data values, such as
https://github.com/jesusff/cmip6-for-cordex/blob/19031e99f4b959499b8ff1e1ccf24dbae51e82b3/CMIP6_studies/Dobler.yaml#L48 
lead to NaN's which ultimately disappear when rendering the table. They are still counted (with unexpected behaviour?) when computing synthesis columns.

In this particular case, it is a model for which the metric could not be computed because the target region (Baltic Sea) is not represented in the model. This is clearly implausible, so we should indicate it explicitly. E.g. by assigning a value, such as -99, out of the valid and plausible ranges, instead of a NaN or empty value.

**Comment by doblerone** [comment]
I can change the value to -99 in the SST/Sea-ice yaml files for non-existing Seas in the GCMs and add a comment to the description.
OK?

**Comment by jesusff** [comment]
ok, I'll test what happens with the tables then

**Comment by jesusff** [comment]
This was fixed in 878b6ee70 and looks good on the table (values greyed out).
