### ISSUE TITLE
license of cordex data based on CMIP6 models 

### ISSUE THREAD

**Issue by larsbuntemeyer** [jesusff/cmip6-for-cordex#14]
Apologies if this is out of scope, but i have a question (or suggestion) concerning the terms of use of future CORDEX-CMIP6 datasets. The current [CORDEX terms of use](https://is-enes-data.github.io/cordex_terms_of_use.pdf) seem to be derived from the [original CMIP5 terms of use](https://pcmdi.llnl.gov/mips/cmip5/terms-of-use-old.html) which seemd to be reasonable. However, [CMIP6 datasets](https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html) are published under a *copyleft* license ([CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)) which means that 

*If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.*

So will CORDEX-CMIP6 datasets be published under a CC BY-SA 4.0 license? Will CORDEX terms of use be updated?

**Comment by jesusff** [comment]
Hi @larsbuntemeyer

this is a bit off-topic here, yes :-) I have no idea. I don't see a way around this viral share-alike license, but I'm no expert in licenses. This has surely been debated, @gnikulin?

For other purposes (e.g. CMIP6 derived products distributed by the IPCC-DDC) the CMIP6 license has been relaxed to CC-BY. Maybe such an agreement can be negotiated for CORDEX-CMIP6 as well.

**Comment by larsbuntemeyer** [comment]
hey, thanks! i was strolling all over github to find something on this topic, so i just posed it here. maybe we can quickly talk about this next week in the GA. i linked this issue in the google-docs agenda...

**Comment by gnikulin** [comment]
This issue has already been shortly discussed and the CORDEX ToU will be updated. There is also an ongoing discussion about updating the CMIP6 data license. Perhaps, we may use the same approach as in the IPCC DDC and relax the CC BY-SA license to the CC BY one with an agreement from the CMIP6 groups of course.
